<?php
declare(strict_types=1);

// Orbit SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

OrbitUtility::setRegistrar(function (OrbitUtility $u): void {
    $u->clean = [OrbitClean::class, 'call'];
    $u->done = [OrbitDone::class, 'call'];
    $u->make_error = [OrbitMakeError::class, 'call'];
    $u->feature_add = [OrbitFeatureAdd::class, 'call'];
    $u->feature_hook = [OrbitFeatureHook::class, 'call'];
    $u->feature_init = [OrbitFeatureInit::class, 'call'];
    $u->fetcher = [OrbitFetcher::class, 'call'];
    $u->make_fetch_def = [OrbitMakeFetchDef::class, 'call'];
    $u->make_context = [OrbitMakeContext::class, 'call'];
    $u->make_options = [OrbitMakeOptions::class, 'call'];
    $u->make_request = [OrbitMakeRequest::class, 'call'];
    $u->make_response = [OrbitMakeResponse::class, 'call'];
    $u->make_result = [OrbitMakeResult::class, 'call'];
    $u->make_point = [OrbitMakePoint::class, 'call'];
    $u->make_spec = [OrbitMakeSpec::class, 'call'];
    $u->make_url = [OrbitMakeUrl::class, 'call'];
    $u->param = [OrbitParam::class, 'call'];
    $u->prepare_auth = [OrbitPrepareAuth::class, 'call'];
    $u->prepare_body = [OrbitPrepareBody::class, 'call'];
    $u->prepare_headers = [OrbitPrepareHeaders::class, 'call'];
    $u->prepare_method = [OrbitPrepareMethod::class, 'call'];
    $u->prepare_params = [OrbitPrepareParams::class, 'call'];
    $u->prepare_path = [OrbitPreparePath::class, 'call'];
    $u->prepare_query = [OrbitPrepareQuery::class, 'call'];
    $u->graphql_body = [OrbitGraphql::class, 'body'];
    $u->graphql_errors = [OrbitGraphql::class, 'errors'];
    $u->result_basic = [OrbitResultBasic::class, 'call'];
    $u->result_body = [OrbitResultBody::class, 'call'];
    $u->result_headers = [OrbitResultHeaders::class, 'call'];
    $u->transform_request = [OrbitTransformRequest::class, 'call'];
    $u->transform_response = [OrbitTransformResponse::class, 'call'];
});
